CREATE TABLE user_account (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',

    phone VARCHAR(20) NOT NULL COMMENT '手机号',

    nickname VARCHAR(64) DEFAULT NULL COMMENT '昵称',

    avatar_url VARCHAR(512) DEFAULT NULL COMMENT '头像',

    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态',

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY uk_phone (phone)

) COMMENT='用户表';